apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-hello-world
  name: node-hello-world
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-hello-world
  type: LoadBalancer
status:
  loadBalancer: {}

